# The name of this file shouldn't be changed, or else the Setup Assistant won't detect it
sensors:
 - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
   point_cloud_topic: /camera/depth/points
   max_range: 10.0
   frame_subsample: 1
   point_subsample: 1
